# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
