# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 03:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20170323_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attachment_caption',
        ),
        migrations.AddField(
            model_name='post',
            name='attachment_type',
            field=models.CharField(choices=[('V', 'Video'), ('I', 'Image')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 3, 25, 38, 629902)),
        ),
    ]
